#!/usr/bin/env bash

echo "Setting up your Linux environment..."

# Install Git
# https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
echo "Installing Git..."
sudo apt-get update
sudo apt-get install git

# Install Stow
echo "Installing Stow..."
sudo apt-get install stow

# Install tmux
echo "Installing tmux..."
sudo apt-get install tmux

# Install fzf
echo "Installing fzf..."
sudo apt-get install fzf

# Install Neovim
mkdir ~/programs
sudo apt-get install ninja-build gettext cmake unzip curl
git clone https://github.com/neovim/neovim ~/programs/nvim
cd ~/programs/nvim
make CMAKE_BUILD_TYPE=RelWithDebInfo
git checkout stable
sudo make install
cd ~

# Clone dotfiles repo
git clone https://github.com/jesuskcapellan/dotfiles.git ~/.dotfiles
cd ~/.dotfiles
if [ ! -d !/.config ]; then
   mkdir ~/.config
fi
if [ ! -d !/.config/nvim ]; then
   mkdir ~/.config/nvim
fi
if [ ! -d !/.config/tmux ]; then
   mkdir ~/.config/tmux
fi
stow --target="$HOME/.config/nvim" nvim
stow --target="$HOME/.config/tmux" tmux
stow --target="$HOME" bash
cd ~/.dotfiles/extras
if [ ! -d ~/.local/bin ]; then
   mkdir ~/.local/bin
fi
stow --target="$HOME/.config" starship
stow --target="$HOME/.local/bin" tmux-sessionizer
source ~/.bashrc

# Install Node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
source ~/.bashrc 
nvm use 18

# Setup Starship
curl -sS https://starship.rs/install.sh | sh
