github.com:
    users:
        jesuskcapellan:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: jesuskcapellan
