set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set-option -g status-position "top"

# Settings
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin"
set -s escape-time 50
set -as terminal-features ",xterm-256color:RGB"
set -g status-position bottom
set -g base-index 1
set-window-option -g mode-keys vi
set -g mouse on

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'janoamaral/tokyo-night-tmux'


# Keybindings
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix
bind r source-file ~/.config/tmux/tmux.conf
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R
bind -r f run-shell "tmux neww ~/.local/bin/sesh"
bind -r C run-shell "tmux neww ~/.local/bin/sesh ~/.config/nvim/"
bind -r H run-shell "tmux neww ~/.local/bin/sesh ~/workplace/InfraMap/src/DCMap/"
bind -r T run-shell "tmux neww ~/.local/bin/sesh ~/workplace/InfraMap/src/InfraMapShared/"
bind -r N run-shell "tmux neww ~/.local/bin/sesh ~/workplace/InfraMap/src/InfraMapCloudCypressTests/"
bind -r S run-shell "tmux neww ~/.local/bin/sesh ~/workplace/InfraMap/src/InfraMapPipelineCDK/"
bind -r M run-shell "tmux neww ~/.local/bin/sesh ~/workplace/InfraMap/src/InfraMapApplicationShell/"
bind -r W run-shell "tmux neww ~/.local/bin/sesh ~/workplace/"
bind -r G run-shell "tmux neww ~/.local/bin/sesh ~/workplace/datagen/src/InfraMapLocalDataGenerator/"
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

# Theme
# set -g @catppuccin_flavor 'mocha'
# set -g @catppuccin_window_number_position 'right'
# set -g @catppuccin_window_status 'no'
# set -g @catppuccin_window_default_text '#W'
# set -g @catppuccin_window_current_fill 'number'k
# set -g @catppuccin_window_current_text '#W'
# set -g @catppuccin_window_current_color '#{E:@thm_surface_2}'
# set -g @catppuccin_date_time_text ' %D - %I:%M %p'
# set -g @catppuccin_status_module_text_bg '#{E:@thm_mantle}'
# set -g @catppuccin_window_status_style 'basic'
# set -g @catppuccin_window_current_style 'basic'
# set -g @catppuccin_status_left_separator "█"
# set -g @catppuccin_status_right_separator "█"

# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# set -g status-left '#{E:@catppuccin_status_session} '
# set -g status-right '#{E:@catppuccin_status_date_time} '
# set -g status-left-length 100
# set -g status-right-length 100

set -g @tokyo-night-tmux_show_git 0

# TPM
run -b '~/.config/tmux/plugins/tpm/tpm'
